### ISSUE TITLE
add align(8) to mail

### ISSUE THREAD

**Issue by mw66** [Cyroxin/Elembuf#4]
https://github.com/Cyroxin/Elembuf/blob/master/source/buffer.d#L292
```
		__gshared ptrdiff_t mail = 0; // Thread sync variable, must fit a pointer.
```
Since this var is atomicLoad & atomicStore, better make it aligned to word size, i.e.

```
		  align(8) __gshared ptrdiff_t mail = 0; // Thread sync variable, must fit a pointer.
```

**Comment by Cyroxin** [comment]
````
align(mail.sizeof) __gshared ptrdiff_t mail = 0;
````

Wouldn't this work better as the size of mail isn't always 8 bytes anyways?
